### ISSUE TITLE
Addition of Min / Max percentage spread

### ISSUE THREAD

**Issue by Puppytherapy** [jazzonaut/IntelliTrader#1]
First !

The addition of min / max percentage spread would be amazing !

The size of the bid-ask spread from one asset to another differs mainly because of the difference in liquidity of each asset.

**Explanation:**
> Percentage difference between highest bid and lowest ask. The smaller the spread the greater the price action / liquidity.

**Comment by jazzonaut** [comment]
On it!

**Comment by jazzonaut** [comment]
Implemented in v0.9.9.7
