### ISSUE TITLE
Enhancement - Process names on linux

### ISSUE THREAD

**Issue by Chingis-Khan** [jazzonaut/IntelliTrader#16]
Hi, would it be possible to use the Instane Name as a process name on Linux, I am running multiple instances and they all show 'dotnet' as their process name.

**Comment by mrhasbean** [comment]
@Chingis-Khan I'm not sure there is any way of doing that while it is running "under" dotnet. I think you would have to build a specific Linux version of the app, in which case it should then appear in the process list with it's name. There are details on building a linux version [here](https://github.com/dotnet/core/blob/master/Documentation/self-contained-linux-apps.md)

**Comment by jazzonaut** [comment]
By the way on Windows it's exactly the same issues, you just get a bunch of dotnet proceses. That's because dotnet acts as a sort of launcher/host for the main program. So it's normal and I'm not sure if we should do anything about it.

**Comment by Chingis-Khan** [comment]
yes, I have solution that works for me, but might not be suitable for others. I modified the start scripts to run in a detached screen assigning each screen a descriptive name (bot1, bot2 etc)

**Comment by mrhasbean** [comment]
@Chingis-Khan you can run them using pm2, the json file to launch them is in the distro, you just edit that for each bot to give it a unique name. That way you can monitor them with the pm2 dashboard. My bad, I was supposed to write a how-to for the wiki but have been a bit sidetracked with getting my business up and running. I'll get to it ASAP.

**Comment by Chingis-Khan** [comment]
what is pm2?
