### ISSUE TITLE
Dumb User Protection System - Coloured Borders

### ISSUE THREAD

**Issue by Chingis-Khan** [jazzonaut/IntelliTrader#22]
Hi, 

Would it be possible to have basic UI theme-ability,   I am running two bots and I have twice altered settigns for the wrong bot.  So I was wondering if we could set the border background colour as a setting to help remind me and perhaps others what bot they are editing

**Comment by jazzonaut** [comment]
Use the InstanceName parameter in core.json to distinguish between different bot instances. It is shown on every page.
